// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title TrustCredRegistry
 * @dev Decentralized academic credential registry storing SHA-256 certificate hashes.
 * Stores lightweight cryptographic proofs and issuance metadata on-chain without raw documents.
 */
contract TrustCredRegistry {
    // Contract Owner / System Admin
    address public owner;

    // Mapping of authorized institution addresses allowed to register/revoke credentials
    mapping(address => bool) public authorizedIssuers;

    // Mapping of authorized institution wallet address to registered college name
    mapping(address => string) public issuerNames;
    mapping(address => string) public issuerCodes;

    // Struct defining on-chain credential record
    struct CredentialRecord {
        string credentialId;       // Unique ID, e.g. TC-2026-89421
        string certificateHash;     // 64-character SHA-256 hex digest
        string institution;        // Issuing institution name
        uint256 issueTimestamp;    // Block timestamp of registration
        bool revoked;              // Revocation status flag
        address issuer;            // Address of registering institution
    }

    // Mapping from unique credentialId to CredentialRecord
    mapping(string => CredentialRecord) private _credentials;

    // Array of all registered credential IDs for enumeration
    string[] private _allCredentialIds;

    // Events
    event CredentialRegistered(
        string indexed credentialId,
        string certificateHash,
        string institution,
        uint256 issueTimestamp,
        address indexed issuer
    );

    event CredentialRevoked(
        string indexed credentialId,
        uint256 revokedTimestamp,
        address indexed revoker
    );

    event IssuerAuthorized(address indexed issuer, string collegeName, string collegeCode);
    event IssuerDeauthorized(address indexed issuer);

    // Modifiers
    modifier onlyOwner() {
        require(msg.sender == owner, "TrustCred: Caller is not contract owner");
        _;
    }

    modifier onlyAuthorizedIssuer() {
        require(
            msg.sender == owner || authorizedIssuers[msg.sender],
            "Unauthorized college wallet. Only registered colleges can issue credentials."
        );
        _;
    }

    constructor() {
        owner = msg.sender;
        authorizedIssuers[msg.sender] = true;
        issuerNames[msg.sender] = "National Institute of Technology & Science";
        issuerCodes[msg.sender] = "NITS-EDU-09";
    }

    /**
     * @notice Authorize an institution address to issue credentials
     * @param issuer Address of the institution
     */
    function authorizeIssuer(address issuer) external onlyOwner {
        require(issuer != address(0), "TrustCred: Invalid issuer address");
        authorizedIssuers[issuer] = true;
        emit IssuerAuthorized(issuer, issuerNames[issuer], issuerCodes[issuer]);
    }

    /**
     * @notice Register and authorize an approved college with metadata
     * @param issuer Address of the institution wallet
     * @param collegeName Official name of the academic institution
     * @param collegeCode Unique institutional identifier code
     */
    function registerApprovedCollege(
        address issuer,
        string memory collegeName,
        string memory collegeCode
    ) external onlyOwner {
        require(issuer != address(0), "TrustCred: Invalid issuer address");
        require(bytes(collegeName).length > 0, "TrustCred: College name required");
        require(bytes(collegeCode).length > 0, "TrustCred: College code required");
        
        authorizedIssuers[issuer] = true;
        issuerNames[issuer] = collegeName;
        issuerCodes[issuer] = collegeCode;
        emit IssuerAuthorized(issuer, collegeName, collegeCode);
    }

    /**
     * @notice Deauthorize an institution address
     * @param issuer Address to deauthorize
     */
    function deauthorizeIssuer(address issuer) external onlyOwner {
        authorizedIssuers[issuer] = false;
        emit IssuerDeauthorized(issuer);
    }

    /**
     * @notice Register a new academic credential on-chain
     * @dev Stores only metadata and SHA-256 hash. Does NOT store PDF or private data.
     * @param credentialId Unique alphanumeric credential identifier (e.g. TC-2026-89421)
     * @param certificateHash The 64-character SHA-256 hash generated by TrustCred
     * @param institution Name of the issuing academic institution
     */
    function registerCredential(
        string memory credentialId,
        string memory certificateHash,
        string memory institution
    ) external onlyAuthorizedIssuer {
        require(bytes(credentialId).length > 0, "TrustCred: Credential ID cannot be empty");
        require(bytes(certificateHash).length == 64, "TrustCred: Invalid SHA-256 hash length (must be 64 hex chars)");
        require(bytes(institution).length > 0, "TrustCred: Institution name cannot be empty");
        
        // Prevent duplicate registration of the same Credential ID
        require(
            bytes(_credentials[credentialId].credentialId).length == 0,
            "TrustCred: Credential ID already registered on blockchain"
        );

        CredentialRecord memory newRecord = CredentialRecord({
            credentialId: credentialId,
            certificateHash: certificateHash,
            institution: institution,
            issueTimestamp: block.timestamp,
            revoked: false,
            issuer: msg.sender
        });

        _credentials[credentialId] = newRecord;
        _allCredentialIds.push(credentialId);

        emit CredentialRegistered(
            credentialId,
            certificateHash,
            institution,
            block.timestamp,
            msg.sender
        );
    }

    /**
     * @notice Retrieve on-chain credential verification record
     * @param credentialId Unique credential identifier
     * @return id Credential ID
     * @return hash SHA-256 certificate hash
     * @return inst Issuing institution
     * @return timestamp Block timestamp when registered
     * @return isRevoked Boolean revoked flag
     * @return issuerAddr Address of the registering entity
     */
    function getCredential(string memory credentialId)
        external
        view
        returns (
            string memory id,
            string memory hash,
            string memory inst,
            uint256 timestamp,
            bool isRevoked,
            address issuerAddr
        )
    {
        CredentialRecord memory record = _credentials[credentialId];
        require(bytes(record.credentialId).length > 0, "TrustCred: Credential not found on blockchain");

        return (
            record.credentialId,
            record.certificateHash,
            record.institution,
            record.issueTimestamp,
            record.revoked,
            record.issuer
        );
    }

    /**
     * @notice Check if a credential exists on-chain without reverting
     * @param credentialId Unique credential identifier
     */
    function credentialExists(string memory credentialId) external view returns (bool) {
        return bytes(_credentials[credentialId].credentialId).length > 0;
    }

    /**
     * @notice Revoke a previously registered credential
     * @dev Does not delete the record; sets revoked flag to true.
     * @param credentialId Unique credential identifier
     */
    function revokeCredential(string memory credentialId) external onlyAuthorizedIssuer {
        CredentialRecord storage record = _credentials[credentialId];
        require(bytes(record.credentialId).length > 0, "TrustCred: Credential not found on blockchain");
        require(!record.revoked, "TrustCred: Credential is already revoked");

        // Only contract owner or the original issuing institution can revoke
        require(
            msg.sender == owner || msg.sender == record.issuer,
            "TrustCred: Only the original issuer or contract owner can revoke this credential"
        );

        record.revoked = true;

        emit CredentialRevoked(credentialId, block.timestamp, msg.sender);
    }

    /**
     * @notice Total number of credentials registered on-chain
     */
    function getTotalCredentials() external view returns (uint256) {
        return _allCredentialIds.length;
    }

    /**
     * @notice Get credential ID at specific index
     */
    function getCredentialIdAtIndex(uint256 index) external view returns (string memory) {
        require(index < _allCredentialIds.length, "TrustCred: Index out of bounds");
        return _allCredentialIds[index];
    }
}
